name: "CI"

env:
  DOTENV_CONFIG_PATH: "./.env.example"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        # Hack to get around failing "ethereumjs-abi The remote archive doesn't match the expected checksum" error
        run: YARN_CHECKSUM_BEHAVIOR=update yarn

      - name: Lint solidity and ts files
        run: yarn lint
